import type { Glossary, TranslationJob } from "./types"

export const mockGlossaries: Glossary[] = [
  {
    id: "1",
    name: "Legal Terms",
    description: "Standard legal terminology for contracts and agreements",
    sourceLanguage: "English",
    targetLanguage: "Spanish",
    termCount: 156,
    terms: [
      { id: "1", source: "Agreement", target: "Acuerdo" },
      { id: "2", source: "Liability", target: "Responsabilidad" },
      { id: "3", source: "Indemnification", target: "Indemnización" },
      { id: "4", source: "Jurisdiction", target: "Jurisdicción" },
      { id: "5", source: "Arbitration", target: "Arbitraje" },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "2",
    name: "Medical Vocabulary",
    description: "Clinical and pharmaceutical terminology",
    sourceLanguage: "English",
    targetLanguage: "German",
    termCount: 243,
    terms: [
      { id: "1", source: "Diagnosis", target: "Diagnose" },
      { id: "2", source: "Treatment", target: "Behandlung" },
      { id: "3", source: "Prescription", target: "Verschreibung" },
    ],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-18"),
  },
  {
    id: "3",
    name: "Technical IT",
    description: "Software and technology terms",
    sourceLanguage: "English",
    targetLanguage: "French",
    termCount: 89,
    terms: [
      { id: "1", source: "Database", target: "Base de données" },
      { id: "2", source: "Interface", target: "Interface" },
    ],
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-02-10"),
  },
]

export const mockTranslationHistory: TranslationJob[] = [
  {
    id: "1",
    documentId: "d1",
    documentName: "Contract_Final_v2.docx",
    sourceLanguage: "English",
    targetLanguage: "Spanish",
    glossaryName: "Legal Terms",
    status: "completed",
    progress: 100,
    startedAt: new Date("2024-02-20T10:30:00"),
    completedAt: new Date("2024-02-20T10:35:00"),
    fileSize: 2456789,
  },
  {
    id: "2",
    documentId: "d2",
    documentName: "Patient_Report_Q1.pdf",
    sourceLanguage: "English",
    targetLanguage: "German",
    glossaryName: "Medical Vocabulary",
    status: "completed",
    progress: 100,
    startedAt: new Date("2024-02-19T14:20:00"),
    completedAt: new Date("2024-02-19T14:28:00"),
    fileSize: 1234567,
  },
  {
    id: "3",
    documentId: "d3",
    documentName: "Technical_Specs.docx",
    sourceLanguage: "English",
    targetLanguage: "French",
    glossaryName: "Technical IT",
    status: "completed",
    progress: 100,
    startedAt: new Date("2024-02-18T09:15:00"),
    completedAt: new Date("2024-02-18T09:22:00"),
    fileSize: 890234,
  },
  {
    id: "4",
    documentId: "d4",
    documentName: "Annual_Report_2024.pdf",
    sourceLanguage: "English",
    targetLanguage: "Japanese",
    status: "completed",
    progress: 100,
    startedAt: new Date("2024-02-17T16:45:00"),
    completedAt: new Date("2024-02-17T16:58:00"),
    fileSize: 5678901,
  },
  {
    id: "5",
    documentId: "d5",
    documentName: "User_Manual_v3.docx",
    sourceLanguage: "English",
    targetLanguage: "Chinese",
    status: "failed",
    progress: 45,
    startedAt: new Date("2024-02-16T11:00:00"),
    fileSize: 3456789,
  },
]

export const languages = [
  "English",
  "Japanese",
  "Vietnamese",
]
